-- AlterTable
ALTER TABLE `address` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `client` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `client_address` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `delivery` MODIFY `date` TIMESTAMP NOT NULL,
    MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `delivery_status` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `maintenance_motor` MODIFY `date` TIMESTAMP NOT NULL,
    MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `motorcycle` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `order_delivery` MODIFY `date` TIMESTAMP NOT NULL,
    MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `permissions` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `position` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `position_permissions` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `status` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `store` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `type_maintenance` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `type_order` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;

-- AlterTable
ALTER TABLE `users` MODIFY `createAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateAt` DATETIME(3) NOT NULL;
