-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 18:42:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EterDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EterDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EterDb` DEFAULT CHARACTER SET utf8 ;
USE `EterDb` ;

-- -----------------------------------------------------
-- Table `EterDb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NULL,
  `place` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filial` VARCHAR(10) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address_id` INT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `store_address_fk_idx` (`address_id` ASC),
  CONSTRAINT `store_address_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `EterDb`.`address` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(60) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `position_id` INT NULL,
  `stats` TINYINT NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `users_position_id_fk_idx` (`position_id` ASC),
  INDEX `user_store_id_fk_idx` (`store_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `users_position_id_fk`
    FOREIGN KEY (`position_id`)
    REFERENCES `EterDb`.`position` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `user_store_id_fk`
    FOREIGN KEY (`store_id`)
    REFERENCES `EterDb`.`store` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`type_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`type_order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`order_delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`order_delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `date` DATETIME NOT NULL,
  `client_id` INT NULL,
  `address_id` INT NULL,
  `type_order_id` INT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `order_delivery_user_fk_idx` (`user_id` ASC),
  INDEX `order_delivery_client_fk_idx` (`client_id` ASC),
  INDEX `order_delivery_type_order_fk_idx` (`type_order_id` ASC),
  INDEX `order_delivery_address_fk_idx` (`address_id` ASC),
  CONSTRAINT `order_delivery_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `EterDb`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `order_delivery_client_fk`
    FOREIGN KEY (`client_id`)
    REFERENCES `EterDb`.`client` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `order_delivery_type_order_fk`
    FOREIGN KEY (`type_order_id`)
    REFERENCES `EterDb`.`type_order` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `order_delivery_address_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `EterDb`.`address` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_delivery_id` INT NULL,
  `user_id` INT NULL,
  `date` DATETIME NOT NULL,
  `motor_kilometers` INT NOT NULL,
  `date_completed` DATETIME NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `delivery_userid_fk,_idx` (`user_id` ASC),
  INDEX `delivery_order_delivery_id_fk_idx` (`order_delivery_id` ASC),
  CONSTRAINT `delivery_userid_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `EterDb`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `delivery_order_delivery_id_fk`
    FOREIGN KEY (`order_delivery_id`)
    REFERENCES `EterDb`.`order_delivery` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`motorcycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`motorcycle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `store_id` INT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `motorcycle_store_id_fk_idx` (`store_id` ASC),
  CONSTRAINT `motorcycle_store_id_fk`
    FOREIGN KEY (`store_id`)
    REFERENCES `EterDb`.`store` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`client_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`client_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NULL,
  `address_id` INT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `client_address_client_fk_idx` (`client_id` ASC),
  INDEX `client_address_addrees_fk_idx` (`address_id` ASC),
  CONSTRAINT `client_address_client_fk`
    FOREIGN KEY (`client_id`)
    REFERENCES `EterDb`.`client` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `client_address_addrees_fk`
    FOREIGN KEY (`address_id`)
    REFERENCES `EterDb`.`address` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`type_maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`type_maintenance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`maintenance_motor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`maintenance_motor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_maintenance_id` INT NULL,
  `motorcycle_id` INT NULL,
  `date` DATETIME NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `location` VARCHAR(45) NULL,
  `photo_receipt` VARCHAR(45) NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `maintenance_motor_motorcycle_fk_idx` (`motorcycle_id` ASC),
  INDEX `maintenance_motor_type_maintenance_fk_idx` (`type_maintenance_id` ASC),
  CONSTRAINT `maintenance_motor_motorcycle_fk`
    FOREIGN KEY (`motorcycle_id`)
    REFERENCES `EterDb`.`motorcycle` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `maintenance_motor_type_maintenance_fk`
    FOREIGN KEY (`type_maintenance_id`)
    REFERENCES `EterDb`.`type_maintenance` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`position_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`position_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `permissions_id` INT NULL,
  `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `position_permissions_user_id_fk_idx` (`user_id` ASC),
  INDEX `position_permissions_permissions_id_fk_idx` (`permissions_id` ASC),
  CONSTRAINT `position_permissions_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `EterDb`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `position_permissions_permissions_id_fk`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `EterDb`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EterDb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `createAt` DATETIME NOT NULL,
  `updateAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `EterDb`.`delivery_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EterDb`.`delivery_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `delivery_id` INT NULL,
  `status_id` INT NULL,
  `createAt` DATETIME NOT NULL,
  `updateAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `delivery_status_delivery_fk_idx` (`delivery_id` ASC),
  INDEX `delivery_status_status_id_fk_idx` (`status_id` ASC),
  CONSTRAINT `delivery_status_delivery_fk`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `EterDb`.`delivery` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `delivery_status_status_id_fk`
    FOREIGN KEY (`status_id`)
    REFERENCES `EterDb`.`status` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
